layout_spectrum: 0
color:
  saturation: 0.5268817
  lightness: 1
  brandStrength: 1
  brandColors:
    - '#44BAED'
    - '#010405'
    - '#0F2934'
    - '#348DB3'
    - '#296F8D'
  rhythmicContrast: 0.05555556
typography_spectrum: 0.469534
name: Kuna
